CREATE TABLE USER
( 
    USER_ID integer AUTO_INCREMENT PRIMARY KEY,
    NAME char(30)  NOT NULL ,
    EMAIL_ADDRESS char(30)  NOT NULL ,
    MOBILE_NUMBER char(15)  NOT NULL ,
    USER_NAME char(20) NOT NULL ,
    PASSWORD char(30) NOT NULL ,
    BIRTH_DATE DATE
);


CREATE TABLE USERREGISTEREDCOURSE
(
    USER_ID integer NOT NULL,
    COURSE_ID integer NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
    UNIQUE (USER_ID, COURSE_ID)
);



